const {
  UPLOAD_BASE_DIR,
  QBITTORRENT_HOST,
  QBITTORRENT_PORT,
  QBITTORRENT_USERNAME,
  QBITTORRENT_PASSWORD,
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  MYSQL_DATABASE,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD
} = process.env;

function requireEnv(name, value) {
  if (!value) {
    throw new Error(`Environment variable "${name}" is required but not provided.`);
  }
  return value;
}

export default {
  UPLOAD_BASE_DIR: UPLOAD_BASE_DIR || '/uploads',

  QBITTORRENT_HOST: requireEnv('QBITTORRENT_HOST', QBITTORRENT_HOST),
  QBITTORRENT_PORT: Number(QBITTORRENT_PORT || 8080),
  QBITTORRENT_USERNAME: requireEnv('QBITTORRENT_USERNAME', QBITTORRENT_USERNAME),
  QBITTORRENT_PASSWORD: requireEnv('QBITTORRENT_PASSWORD', QBITTORRENT_PASSWORD),

  MYSQL_HOST: requireEnv('MYSQL_HOST', MYSQL_HOST),
  MYSQL_PORT: Number(MYSQL_PORT || 3306),
  MYSQL_USERNAME: requireEnv('MYSQL_USERNAME', MYSQL_USERNAME),
  MYSQL_PASSWORD: requireEnv('MYSQL_PASSWORD', MYSQL_PASSWORD),
  MYSQL_DATABASE: requireEnv('MYSQL_DATABASE', MYSQL_DATABASE),

  REDIS_HOST: requireEnv('REDIS_HOST', REDIS_HOST),
  REDIS_PORT: Number(REDIS_PORT || 6379),
  REDIS_PASSWORD: REDIS_PASSWORD || ''
};
